server:
  port: 8080

spring:
  application:
    name: resource-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


rabbitmq:
  queue:
    name: songs_queue
  exchange:
    name: songs_exchange
  routing:
    key: songs_routing_key

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka