server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        songMetadata-in-0:
          destination: values-topic
          group: processor
        songMetadata-out-0:
          destination: song-metadata-values-topic

rabbitmq:
  queue:
    name: songs_queue
  exchange:
    name: songs_exchange
  routing:
    key: songs_routing_key