server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


rabbitmq:
  queue:
    name: songs_queue
  exchange:
    name: songs_exchange
  routing:
    key: songs_routing_key