spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: http://localhost:8087/
          predicates:
            - Path=/resources/**
        - id: song-service
          uri: http://localhost:8084/
          predicates:
            - Path=/songs/**
  main:
    web-application-type: reactive

server:
  port: 8080

eureka:
  instance:
    hostname: localhost



